apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: client-storagarage
  namespace: ndmastery
  labels:
    app.kubernetes.io/name: client-storagarage
    app.kubernetes.io/part-of: ndmastery
    app.kubernetes.io/managed-by: argo-rollouts
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: client-storagarage
