apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - traefik/middlewares.yaml
  - cert-manager/clusterissuer-letsencrypt.yaml
  - network/default-deny.yaml
  - network/platform-allow.yaml
  - generated/resource-policy.yaml
