apiVersion: v1
kind: Service
metadata:
  name: web-calconversion-stable
  namespace: ndmastery
  labels:
    app.kubernetes.io/name: web-calconversion
    app.kubernetes.io/part-of: ndmastery
    app.kubernetes.io/managed-by: argo-rollouts
    rollouts.argoproj.io/service-role: stable
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3003
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: web-calconversion
---
apiVersion: v1
kind: Service
metadata:
  name: web-calconversion-canary
  namespace: ndmastery
  labels:
    app.kubernetes.io/name: web-calconversion
    app.kubernetes.io/part-of: ndmastery
    app.kubernetes.io/managed-by: argo-rollouts
    rollouts.argoproj.io/service-role: canary
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3003
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: web-calconversion
