apiVersion: v1
kind: ConfigMap
metadata:
  name: server-ndmastery-config
  namespace: ndmastery
  labels:
    app.kubernetes.io/name: server-ndmastery
    app.kubernetes.io/part-of: ndmastery
    app.kubernetes.io/managed-by: argo-rollouts
data:
  NODE_ENV: "production"
  PORT: "4000"
  HOST: "0.0.0.0"
  PUBLIC_ORIGIN: "https://server.ndmastery.com"
  ORIGIN: "https://server.ndmastery.com"
  GATEWAY_HOST: "0.0.0.0"
  GATEWAY_PORT: "4000"
  SSO_SITE_URL: "https://sso.ndmastery.com"
  SSO_ISSUER: "https://sso.ndmastery.com"
  SSO_WEBAUTHN_RP_ID: "sso.ndmastery.com"
